# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Install fyne and fyne-cross
      run: |
        go install fyne.io/fyne/v2/cmd/fyne@latest
        go install github.com/fyne-io/fyne-cross@latest

    - name: Build Windows
      run: |
        fyne-cross \
          windows \
          -debug -no-cache -app-id me.goodbee.g0chat \
          -name g0chat.exe
          
    - name: Build Linux
      run: |
        fyne-cross \
          linux \
          -debug -no-cache -app-id me.goodbee.g0chat \
          -name g0chat
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: /home/runner/work/g0chat/g0chat/fyne-cross/dist/
  buildMac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Install fyne and fyne-cross
      run: |
        go install fyne.io/fyne/v2/cmd/fyne@latest
        go install github.com/fyne-io/fyne-cross@latest

    - name: Install Podman
      run: |
        brew install podman
        podman machine init

    - name: Build Mac
      run: |
        fyne-cross \
        darwin \
        -debug -no-cache -app-id me.goodbee.g0chat \
        -name g0chat

        
